# Generated by Django 4.2.30 on 2026-06-14 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Производитель')),
                ('material_type', models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG'), ('ABS', 'ABS'), ('TPU', 'TPU/Flex'), ('NYLON', 'Nylon')], max_length=10, verbose_name='Тип пластика')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за катушку (руб)')),
                ('total_weight_g', models.PositiveIntegerField(default=1000, verbose_name='Вес катушки (грамм)')),
                ('remaining_weight_g', models.PositiveIntegerField(default=1000, verbose_name='Остаток пластика (грамм)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель принтера')),
                ('power_consumption_watts', models.PositiveIntegerField(default=350, verbose_name='Энергопотребление (Вт)')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость принтера (руб)')),
                ('estimated_lifespan_hours', models.PositiveIntegerField(default=2000, verbose_name='Ресурс до ТО/замены (часов)')),
                ('total_hours_printed', models.FloatField(default=0.0, verbose_name='Всего отработано часов')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200, verbose_name='Название модели')),
                ('print_time_hours', models.FloatField(verbose_name='Время печати (часов)')),
                ('sliced_weight_g', models.PositiveIntegerField(verbose_name='Вес по слайсеру (грамм)')),
                ('electricity_rate_kwh', models.DecimalField(decimal_places=2, default=5.5, max_digits=5, verbose_name='Тариф за кВтч (руб)')),
                ('is_success', models.BooleanField(default=True, verbose_name='Успешная печать')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('plastic_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость пластика')),
                ('electricity_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость электричества')),
                ('wear_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость износа')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Итоговая себестоимость')),
                ('filament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='calculator.filament', verbose_name='Пластик')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='calculator.printer', verbose_name='Принтер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
